/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sun Jul  2 11:35:42 2017";
extern const char kBuilderName[] = "renguifu";
extern const char kHostName[] = "renguifudeMacBook-Pro.local";
extern const char kCompiler[] = "GCC 4.2.1";
}}
